#pragma once

#include <AP_HAL/AP_HAL_Boards.h>
#include <SRV_Channel/SRV_Channel_config.h>

#ifndef HAL_WITH_ESC_TELEM
#define HAL_WITH_ESC_TELEM ((NUM_SERVO_CHANNELS > 0) && ((HAL_SUPPORT_RCOUT_SERIAL || HAL_MAX_CAN_PROTOCOL_DRIVERS)))
#endif

#ifndef AP_EXTENDED_ESC_TELEM_ENABLED
#define AP_EXTENDED_ESC_TELEM_ENABLED HAL_ENABLE_DRONECAN_DRIVERS
#endif

#ifndef AP_ESC_TELEM_2BLD6010_ENABLED
#if HAL_WITH_ESC_TELEM && !defined(HAL_BUILD_AP_PERIPH) && BOARD_FLASH_SIZE > 1024
#define AP_ESC_TELEM_2BLD6010_ENABLED 1
#else
#define AP_ESC_TELEM_2BLD6010_ENABLED 0
#endif
#endif

#if AP_ESC_TELEM_2BLD6010_ENABLED && !HAL_WITH_ESC_TELEM
    #error "AP_ESC_TELEM_2BLD6010_ENABLED requires HAL_WITH_ESC_TELEM"
#endif

#if AP_EXTENDED_ESC_TELEM_ENABLED && !HAL_WITH_ESC_TELEM
    #error "AP_EXTENDED_ESC_TELEM_ENABLED requires HAL_WITH_ESC_TELEM"
#endif
